Repository Smash-Keyboard-Studios/Meltdown, pull requests merged in 2024-02, with the labels that each got.

#71 Gauge Script Development
  StudioUnityProject/Assets/Scenes/Levels/Level 3/Level 3 - Fire Tutorial.unity
  StudioUnityProject/Assets/Scripts/Puzzle Elements/Steam Generator/GaugeIndicator.cs
Labels: test

#74 Item Grab System
  StudioUnityProject/Assets/Scenes/Item Grab Testing.unity
  StudioUnityProject/Assets/Scripts/Item Grab/PickupController.cs
  StudioUnityProject/ProjectSettings/TagManager.asset
Labels: old base

#86 created security door
  StudioUnityProject/Assets/Prefabs/Puzzle.meta
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals.meta
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/Button pedistal.prefab
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/Button pedistal.prefab.meta
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/SingleUseDoorNormalPrefab.prefab
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/SingleUseDoorNormalPrefab.prefab.meta
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/SingleUseDoorTimerPrefab.prefab
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/SingleUseDoorTimerPrefab.prefab.meta
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/ToggleDoorNormalPrefab.prefab
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/ToggleDoorNormalPrefab.prefab.meta
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/ToggleDoorTimerPrefab.prefab
  StudioUnityProject/Assets/Prefabs/Puzzle/Button pedistals/ToggleDoorTimerPrefab.prefab.meta
  StudioUnityProject/Assets/Prefabs/door/Security door.prefab
  StudioUnityProject/Assets/Prefabs/door/Security door.prefab.meta
  StudioUnityProject/Assets/Scenes/Testing Scenes/VinceMakesMeSad(.unity
  StudioUnityProject/Assets/Scenes/Testing Scenes/VinceMakesMeSad(.unity.meta
  StudioUnityProject/Assets/Scripts/Player/Player Interaction/buttonScript.cs
  StudioUnityProject/Assets/Scripts/Puzzle Elements/Buttons/ButtonInteraction.cs
  StudioUnityProject/Assets/Scripts/Puzzle Elements/door/SecurityDoor.cs
  StudioUnityProject/Assets/Scripts/Puzzle Elements/door/SecurityDoor.cs.meta
  StudioUnityProject/ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: Programming

#96 fixed drawers on desk
  StudioUnityProject/Assets/Models/Props/28/Materials/Desk_Body.mat
  StudioUnityProject/Assets/Models/Props/28/Materials/Desk_Body.mat.meta
  StudioUnityProject/Assets/Models/Props/28/Materials/Desk_drawers.mat
  StudioUnityProject/Assets/Models/Props/28/Materials/Desk_drawers.mat.meta
  StudioUnityProject/Assets/Models/Props/28/Models/28_Desk_v6.fbx
  StudioUnityProject/Assets/Models/Props/28/Models/28_Desk_v6.fbx.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5AO.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5AO.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5AO_5.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5AO_5.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5Height.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5Height.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5Height_4.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5Height_4.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5Normal.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5Normal.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5Normal_3.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5Normal_3.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5basecolour.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5basecolour.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5basecolour_1.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5basecolour_1.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5basemetallic.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5basemetallic.png.meta
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5basemetallic_2.png
  StudioUnityProject/Assets/Models/Props/28/TextureMaps/28_desk_v6/28_Desk_v5basemetallic_2.png.meta
Labels: Artist

#85 Checkpoint doors
  StudioUnityProject/Assets/Scenes/Testing Scenes/CheckpointDoorsTesting.unity
  StudioUnityProject/Assets/Scenes/Testing Scenes/CheckpointDoorsTesting.unity.meta
  StudioUnityProject/Assets/Scripts/CheckpointDoorTrigger.cs
  StudioUnityProject/Assets/Scripts/CheckpointDoorTrigger.cs.meta
Labels: Programming

#92 Continued Gauge Script Development
  StudioUnityProject/Assets/Scripts/Puzzle Elements/Steam Generator/GaugeIndicator.cs
  StudioUnityProject/Assets/Scripts/Puzzle Elements/Steam Generator/SteamGenerator.cs
Labels: Programming, Dont delete

#100 Level3 changed
  StudioUnityProject/Assets/Models/Props/23/TextureMaps/T.23_FumeGlass_Normal.png.meta
  StudioUnityProject/Assets/Prefabs/IceWall.prefab
  StudioUnityProject/Assets/Scenes/Levels/Level 3/Level 3 - Fire Tutorial.unity
  StudioUnityProject/Assets/Scenes/Levels/Level 3/Level 3 - Fire Tutorial/LightingData.asset
  StudioUnityProject/Assets/Scenes/Levels/Level 3/Level 3 - Fire Tutorial/ReflectionProbe-0.exr
  StudioUnityProject/Assets/level design/level 2/LevelDesignPrefabs/Decorations/CAataat.PNG
  StudioUnityProject/Assets/level design/level 2/LevelDesignPrefabs/Decorations/CAataat.PNG.meta
  StudioUnityProject/Assets/level design/level 2/LevelDesignPrefabs/Decorations/Materials.meta
  StudioUnityProject/Assets/level design/level 2/LevelDesignPrefabs/Decorations/Materials/CAataat 1.mat
  StudioUnityProject/Assets/level design/level 2/LevelDesignPrefabs/Decorations/Materials/CAataat 1.mat.meta
  StudioUnityProject/Assets/level design/level 2/LevelDesignPrefabs/Decorations/Materials/CAataat.mat
  StudioUnityProject/Assets/level design/level 2/LevelDesignPrefabs/Decorations/Materials/CAataat.mat.meta
  StudioUnityProject/ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: Designer, Dont delete
