Repository Smash-Keyboard-Studios/Meltdown, pull requests merged in 2024-03, with the labels that each got.

#91 Added optional amounts to pedestals and ice wall
  StudioUnityProject/Assets/Materials/M_Electricity.mat
  StudioUnityProject/Assets/Materials/M_Electricity.mat.meta
  StudioUnityProject/Assets/Prefabs/Fan/Fan.prefab
  StudioUnityProject/Assets/Prefabs/Fan/FanBlade.prefab
  StudioUnityProject/Assets/Prefabs/Fan/FanBlade.prefab.meta
  StudioUnityProject/Assets/Prefabs/IceWall.prefab
  StudioUnityProject/Assets/Prefabs/Pedestals/Large Fire Pedestal.prefab
  StudioUnityProject/Assets/Prefabs/Pedestals/Large Ice Pedestal.prefab
  StudioUnityProject/Assets/Prefabs/Pedestals/Small Fire Pedestal.prefab
  StudioUnityProject/Assets/Prefabs/Pedestals/Small Ice Pedestal.prefab
  StudioUnityProject/Assets/Prefabs/Water.prefab
  StudioUnityProject/Assets/Scenes/Testing Scenes/Soph.unity
  StudioUnityProject/Assets/Scenes/Testing Scenes/Soph.unity.meta
  StudioUnityProject/Assets/Scripts/BasicLogic.cs
  StudioUnityProject/Assets/Scripts/BasicLogic.cs.meta
  StudioUnityProject/Assets/Scripts/Fire Mechanics/IceWall.cs
  StudioUnityProject/Assets/Scripts/Fire Mechanics/LargeFirePedestal.cs
  StudioUnityProject/Assets/Scripts/Fire Mechanics/SmallFirePedestal.cs
  StudioUnityProject/Assets/Scripts/Ice Mechanics/FanSpin.cs
  StudioUnityProject/Assets/Scripts/Ice Mechanics/LargeIcePedestal.cs
  StudioUnityProject/Assets/Scripts/Ice Mechanics/SmallIcePedestal.cs
  StudioUnityProject/Assets/Scripts/Player/Gun/AmmoController.cs
  StudioUnityProject/Assets/Scripts/Player/Player Interaction/InteractiveObject.cs
  StudioUnityProject/Assets/Scripts/Player/Player Interaction/PlayerInteractionScript.cs
Labels: Programming

#102 Fixed a using in code
  StudioUnityProject/Assets/Scenes/Testing Scenes/All Props.unity
  StudioUnityProject/Assets/Scripts/UI/PauseMenu.cs
  StudioUnityProject/ProjectSettings/EditorBuildSettings.asset
  StudioUnityProject/ProjectSettings/ProjectSettings.asset
Labels: hotfix

#107 objects can have fire effects that linger and then destroys the objec…
  StudioUnityProject/Assets/Materials/Fire.mat
  StudioUnityProject/Assets/Materials/Fire.mat.meta
  StudioUnityProject/Assets/Materials/Smoke.mat
  StudioUnityProject/Assets/Materials/Smoke.mat.meta
  StudioUnityProject/Assets/Prefabs/Fire.prefab
  StudioUnityProject/Assets/Prefabs/Fire.prefab.meta
  StudioUnityProject/Assets/Scenes/Testing Scenes/Fire.unity
  StudioUnityProject/Assets/Scenes/Testing Scenes/Fire.unity.meta
  StudioUnityProject/Assets/Scripts/AttachParticleSystem.cs
  StudioUnityProject/Assets/Scripts/AttachParticleSystem.cs.meta
  StudioUnityProject/ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: Programming

#84 Ice Block Dispenser
  StudioUnityProject/Assets/DestroyIceBlock.cs
  StudioUnityProject/Assets/DestroyIceBlock.cs.meta
  StudioUnityProject/Assets/Prefabs/Block Dispenser.meta
  StudioUnityProject/Assets/Prefabs/Block Dispenser/ButtonForTest.prefab
  StudioUnityProject/Assets/Prefabs/Block Dispenser/ButtonForTest.prefab.meta
  StudioUnityProject/Assets/Prefabs/Block Dispenser/Ice Cube Spawner 27.2.24.prefab
  StudioUnityProject/Assets/Prefabs/Block Dispenser/Ice Cube Spawner 27.2.24.prefab.meta
  StudioUnityProject/Assets/Prefabs/Block Dispenser/_ice block cube_.prefab
  StudioUnityProject/Assets/Prefabs/Block Dispenser/_ice block cube_.prefab.meta
  StudioUnityProject/Assets/Scenes/Ice Block Dispenser.unity
  StudioUnityProject/Assets/Scenes/Ice Block Dispenser.unity.meta
  StudioUnityProject/Assets/Scripts/IceBlockDestroyer.cs
  StudioUnityProject/Assets/Scripts/IceBlockDestroyer.cs.meta
  StudioUnityProject/Assets/Scripts/Puzzle Elements/IceCubeSpawner.cs
  StudioUnityProject/Assets/Scripts/Puzzle Elements/IceCubeSpawner.cs.meta
  StudioUnityProject/ProjectSettings/TagManager.asset
Labels: Programming, Changes required

#109 Save system and elemental projectils
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/21_Door_v2_lambert2_MaskMap.png.meta
  StudioUnityProject/Assets/New Physic Material.physicMaterial
  StudioUnityProject/Assets/New Physic Material.physicMaterial.meta
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/Fire.mat
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/Fire.mat.meta
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/Fire.prefab
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/FireScorch.prefab
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/FireScorch.prefab.meta
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/Ice.mat
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/Ice.mat.meta
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/Ice.prefab
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/IceMarks.prefab
  StudioUnityProject/Assets/Prefabs/Elemetnal Weapon/IceMarks.prefab.meta
  StudioUnityProject/Assets/Prefabs/Player/PlayerHolder.prefab
  StudioUnityProject/Assets/Resources/Backup boot/BackupBoot.prefab
  StudioUnityProject/Assets/Scenes/Testing Scenes/PlayerMovementRedesign.unity
  StudioUnityProject/Assets/Scripts/Player/Gun/Fire.cs
  StudioUnityProject/Assets/Scripts/Player/Gun/Gun.cs
  StudioUnityProject/Assets/Scripts/Player/Gun/Ice.cs
  StudioUnityProject/Assets/Scripts/Player/Item Grab/PickupController.cs
  StudioUnityProject/Assets/Scripts/Player/Player movement/PlayerMovementController.cs
  StudioUnityProject/Assets/Scripts/Systems/Save System/SaveData.cs
  StudioUnityProject/Assets/Scripts/Systems/Save System/SaveManager.cs
  StudioUnityProject/Assets/Settings/High_PipelineAsset_ForwardRenderer.asset
  StudioUnityProject/Assets/Settings/Low_PipelineAsset_ForwardRenderer.asset
  StudioUnityProject/Assets/Settings/Medium_PipelineAsset_ForwardRenderer.asset
  StudioUnityProject/Assets/Settings/Ultra_PipelineAsset_ForwardRenderer.asset
  StudioUnityProject/Assets/Settings/Very High_PipelineAsset_ForwardRenderer.asset
  StudioUnityProject/Assets/Settings/Very Low_PipelineAsset_ForwardRenderer.asset
  StudioUnityProject/ProjectSettings/TagManager.asset
Labels: Programming

#113 Added decorative test tubes
  StudioUnityProject/Assets/Models/Props/test_tube_no_stopper.fbx
  StudioUnityProject/Assets/Models/Props/test_tube_no_stopper.fbx.meta
  StudioUnityProject/Assets/Models/Props/test_tube_stopper.fbx
  StudioUnityProject/Assets/Models/Props/test_tube_stopper.fbx.meta
Labels: Artist

#121 Added 2 types of wall for the Lab + Materials
  StudioUnityProject/Assets/Models/Environmental/LabCorner_25.fbx
  StudioUnityProject/Assets/Models/Environmental/LabCorner_25.fbx.meta
  StudioUnityProject/Assets/Models/Environmental/LabWallV1_25.fbx
  StudioUnityProject/Assets/Models/Environmental/LabWallV1_25.fbx.meta
  StudioUnityProject/Assets/Models/Environmental/LabWallV2_25.fbx
  StudioUnityProject/Assets/Models/Environmental/LabWallV2_25.fbx.meta
  StudioUnityProject/Assets/Models/Environmental/Materials/25_Corner.mat
  StudioUnityProject/Assets/Models/Environmental/Materials/25_Corner.mat.meta
  StudioUnityProject/Assets/Models/Environmental/Materials/25_LabV1.mat
  StudioUnityProject/Assets/Models/Environmental/Materials/25_LabV1.mat.meta
  StudioUnityProject/Assets/Models/Environmental/Materials/25_LabV2.mat
  StudioUnityProject/Assets/Models/Environmental/Materials/25_LabV2.mat.meta
  StudioUnityProject/Assets/Models/Environmental/Materials/Corner.mat
  StudioUnityProject/Assets/Models/Environmental/Materials/Corner.mat.meta
  StudioUnityProject/Assets/Models/Environmental/Materials/Wall1.mat
  StudioUnityProject/Assets/Models/Environmental/Materials/Wall1.mat.meta
  StudioUnityProject/Assets/Models/Environmental/Materials/lambert1.mat
  StudioUnityProject/Assets/Models/Environmental/Materials/lambert1.mat.meta
  StudioUnityProject/Assets/Models/Environmental/OfficeDoor_25.fbx
  StudioUnityProject/Assets/Models/Environmental/OfficeDoor_25.fbx.meta
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabCorner_25_Corner_BaseMap.png
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabCorner_25_Corner_BaseMap.png.meta
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV1_25_Wall1_BaseMap.png
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV1_25_Wall1_BaseMap.png.meta
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV1_25_Wall1_MaskMap.png
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV1_25_Wall1_MaskMap.png.meta
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV1_25_Wall1_Normal.png
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV1_25_Wall1_Normal.png.meta
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV2_25_lambert1_BaseMap.png
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV2_25_lambert1_BaseMap.png.meta
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV2_25_lambert1_MaskMap.png
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV2_25_lambert1_MaskMap.png.meta
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV2_25_lambert1_Normal.png
  StudioUnityProject/Assets/Models/Environmental/Texture Maps/LabWallV2_25_lambert1_Normal.png.meta
  StudioUnityProject/Assets/Scenes/Semi_EnvArt.unity
  StudioUnityProject/Assets/Scenes/Semi_EnvArt.unity.meta
Labels: Artist

#119 Ice tutorial
  StudioUnityProject/Assets/Scenes/Levels/Level 5.meta
  StudioUnityProject/Assets/Scenes/Levels/Level 5/Ice Tutorial.unity
  StudioUnityProject/Assets/Scenes/Levels/Level 5/Ice Tutorial.unity.meta
  StudioUnityProject/Assets/level design/LEVELS/new level prefabs/Stairs.prefab
  StudioUnityProject/Assets/level design/LEVELS/new level prefabs/Stairs.prefab.meta
Labels: Designer

#132 Alex moving platforms
  MeltdownUnity/Assets/Prefabs/movingPlatform.prefab
  MeltdownUnity/Assets/Prefabs/movingPlatform.prefab.meta
  MeltdownUnity/Assets/Prefabs/movingPlatformHorizontal.prefab
  MeltdownUnity/Assets/Prefabs/movingPlatformHorizontal.prefab.meta
  MeltdownUnity/Assets/Scripts/Puzzle Elements/MovingPlatforms.cs
  MeltdownUnity/Assets/Scripts/Puzzle Elements/MovingPlatforms.cs.meta
Labels: Programming

#162 Change Log
  MeltdownUnity/Assets/Models/Props/FBX/Cig unlit 9.fbx
  MeltdownUnity/Assets/Models/Props/FBX/Cig unlit 9.fbx.meta
  MeltdownUnity/Assets/Models/Props/FBX/Elevator AMENDED V7.fbx
  MeltdownUnity/Assets/Models/Props/FBX/Elevator AMENDED V7.fbx.meta
  MeltdownUnity/Assets/Models/Props/FBX/Lighter ZIPPO OPEN V4.fbx
  MeltdownUnity/Assets/Models/Props/FBX/Lighter ZIPPO OPEN V4.fbx.meta
  MeltdownUnity/Assets/Models/Props/Materials/24_M_CIgarette UNLIT.mat
  MeltdownUnity/Assets/Models/Props/Materials/24_M_CIgarette UNLIT.mat.meta
  MeltdownUnity/Assets/Models/Props/Materials/24_M_Elevator Amended.mat
  MeltdownUnity/Assets/Models/Props/Materials/24_M_Elevator Amended.mat.meta
  MeltdownUnity/Assets/Models/Props/Materials/24_M_Lighter Zippo.mat
  MeltdownUnity/Assets/Models/Props/Materials/24_M_Lighter Zippo.mat.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_AO.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_AO.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_Albedo.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_Albedo.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_Height.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_Height.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_Metalic.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_Metalic.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_Normal.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Cig unlit 9_lambert1_Normal.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_AO.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_AO.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_Albedo.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_Albedo.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_Height.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_Height.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_Metalic.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_Metalic.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_Normal.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Elevator AMENDED V6_lambert1_Normal.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_AO.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_AO.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_Albedo.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_Albedo.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_Height.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_Height.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_Metalic.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_Metalic.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_Normal.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Lighter OPEN V2_lambert1_Normal.png.meta
Labels: Artist

#217 Added Models and Materials
  MeltdownUnity/Assets/Models/Props/FBX/Desk Lamp.fbx
  MeltdownUnity/Assets/Models/Props/FBX/Desk Lamp.fbx.meta
  MeltdownUnity/Assets/Models/Props/FBX/Evaporating Dish.fbx
  MeltdownUnity/Assets/Models/Props/FBX/Evaporating Dish.fbx.meta
  MeltdownUnity/Assets/Models/Props/FBX/Wash_Bottle_2.fbx
  MeltdownUnity/Assets/Models/Props/FBX/Wash_Bottle_2.fbx.meta
  MeltdownUnity/Assets/Models/Props/Materials/Evaporating Dish.mat
  MeltdownUnity/Assets/Models/Props/Materials/Evaporating Dish.mat.meta
  MeltdownUnity/Assets/Models/Props/Materials/Lamp_Texture.mat
  MeltdownUnity/Assets/Models/Props/Materials/Lamp_Texture.mat.meta
  MeltdownUnity/Assets/Models/Props/Materials/Wash_Bottle_2_Texture.mat
  MeltdownUnity/Assets/Models/Props/Materials/Wash_Bottle_2_Texture.mat.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Desk Lamp_lambert1_BaseMap.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Desk Lamp_lambert1_BaseMap.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Desk Lamp_lambert1_MaskMap.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Desk Lamp_lambert1_MaskMap.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Desk Lamp_lambert1_Normal.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Desk Lamp_lambert1_Normal.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Evaporating Dish_standardSurface1_BaseMap.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Evaporating Dish_standardSurface1_BaseMap.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Evaporating Dish_standardSurface1_MaskMap.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Evaporating Dish_standardSurface1_MaskMap.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Evaporating Dish_standardSurface1_Normal.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Evaporating Dish_standardSurface1_Normal.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Wash Bottle 2_standardSurface1_BaseMap.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Wash Bottle 2_standardSurface1_BaseMap.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Wash Bottle 2_standardSurface1_MaskMap.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Wash Bottle 2_standardSurface1_MaskMap.png.meta
  MeltdownUnity/Assets/Models/Props/Texture Maps/Wash Bottle 2_standardSurface1_Normal.png
  MeltdownUnity/Assets/Models/Props/Texture Maps/Wash Bottle 2_standardSurface1_Normal.png.meta
Labels: Artist
