Repository Smash-Keyboard-Studios/Meltdown, pull requests merged in 2024-04, with the labels that each got.

#268 Changed the UI elements
  MeltdownUnity/Assets/Prefabs/Player/PlayerHolder.prefab
  MeltdownUnity/Assets/Scenes/UI/Main Menu.unity
  MeltdownUnity/Assets/Scripts/Systems/Save System/SaveData.cs
  MeltdownUnity/Assets/Scripts/UI/MainMenu.cs
  MeltdownUnity/Assets/Scripts/UI/PauseMenu.cs
  MeltdownUnity/Assets/UIButton_Box_Blue.png
  MeltdownUnity/Assets/UIButton_Box_Blue.png.meta
  MeltdownUnity/Assets/UIButton_Box_Empty.png
  MeltdownUnity/Assets/UIButton_Box_Empty.png.meta
  MeltdownUnity/Assets/UIButton_Box_Red.png
  MeltdownUnity/Assets/UIButton_Box_Red.png.meta
Labels: programming

#272 Added bunch of Environment assets
  MeltdownUnity/Assets/Models/Environmental/CornerInward_25.fbx
  MeltdownUnity/Assets/Models/Environmental/CornerInward_25.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/CornerOutward_25.fbx
  MeltdownUnity/Assets/Models/Environmental/CornerOutward_25.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/FlatWall2x4_25.fbx
  MeltdownUnity/Assets/Models/Environmental/FlatWall2x4_25.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/HeightTile_25.fbx
  MeltdownUnity/Assets/Models/Environmental/HeightTile_25.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/LabWall2x3_25.fbx
  MeltdownUnity/Assets/Models/Environmental/LabWall2x3_25.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/LabWallPipe2x3_25.fbx
  MeltdownUnity/Assets/Models/Environmental/LabWallPipe2x3_25.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/WallConnectorL_25.fbx
  MeltdownUnity/Assets/Models/Environmental/WallConnectorL_25.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/WallConnectorR_25.fbx
  MeltdownUnity/Assets/Models/Environmental/WallConnectorR_25.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/WallVent1x4_25.fbx
  MeltdownUnity/Assets/Models/Environmental/WallVent1x4_25.fbx.meta
  MeltdownUnity/Assets/Models/NewStuffSamEnv.unity
  MeltdownUnity/Assets/Models/NewStuffSamEnv.unity.meta
Labels: artist

#277 Gauge Script Bonus Development
  MeltdownUnity/Assets/Scripts/Managers/PuzzleManager/PuzzleManager_A.cs
  MeltdownUnity/Assets/Scripts/Managers/PuzzleManager/PuzzleManager_A.cs.meta
  MeltdownUnity/Assets/Scripts/Puzzle Elements/Steam Generator/GaugeIndicator.cs
Labels: programming

#285 Moving platform fixes
  MeltdownUnity/Assets/Prefabs/Puzzle/Moving Platforms/MovingPlatHorizontal.prefab
  MeltdownUnity/Assets/Prefabs/Puzzle/Moving Platforms/MovingPlatHorizontalRailless Variant.prefab
  MeltdownUnity/Assets/Prefabs/Puzzle/Moving Platforms/MovingPlatVertical.prefab
  MeltdownUnity/Assets/Scenes/Testing Scenes/PlayerMovementRedesign.unity
  MeltdownUnity/Assets/Scripts/Puzzle Elements/MovingPlatform/TriggerDetection.cs
Labels: programming, hotfix

#291 Change Log
  MeltdownUnity/Assets/Models/Environmental/FBX/Catwalk and stairs/Alt versions.meta
  MeltdownUnity/Assets/Models/Environmental/FBX/Catwalk and stairs/Alt versions/Catwalk Long V1 ALT.fbx
  MeltdownUnity/Assets/Models/Environmental/FBX/Catwalk and stairs/Alt versions/Catwalk Long V1 ALT.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/FBX/Catwalk and stairs/Alt versions/Catwalk corner V1 ALT.fbx
  MeltdownUnity/Assets/Models/Environmental/FBX/Catwalk and stairs/Alt versions/Catwalk corner V1 ALT.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/FBX/Catwalk and stairs/Alt versions/Staricase V3 ALT.fbx
  MeltdownUnity/Assets/Models/Environmental/FBX/Catwalk and stairs/Alt versions/Staricase V3 ALT.fbx.meta
  MeltdownUnity/Assets/Models/Environmental/Materials/Catwalk/M_24_Catwalk corner no rails.mat
  MeltdownUnity/Assets/Models/Environmental/Materials/Catwalk/M_24_Catwalk corner no rails.mat.meta
  MeltdownUnity/Assets/Models/Environmental/Materials/Catwalk/M_24_Catwalk long no rails.mat
  MeltdownUnity/Assets/Models/Environmental/Materials/Catwalk/M_24_Catwalk long no rails.mat.meta
  MeltdownUnity/Assets/Models/Environmental/Materials/Catwalk/M_24_Stair 2 Alt.mat
  MeltdownUnity/Assets/Models/Environmental/Materials/Catwalk/M_24_Stair 2 Alt.mat.meta
  MeltdownUnity/Assets/Models/Environmental/Materials/Catwalk/M_24_Stair ALT.mat
  MeltdownUnity/Assets/Models/Environmental/Materials/Catwalk/M_24_Stair ALT.mat.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_AO.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_AO.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_Albedo.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_Albedo.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_Height.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_Height.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_Metalic.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_Metalic.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_Normal.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk Long V1 ALT_lambert1_Normal.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_AO.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_AO.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_Albedo.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_Albedo.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_Height.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_Height.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_Metalic.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_Metalic.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_Normal.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Catwalk corner V1 ALT_lambert1_Normal.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_AO.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_AO.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_Albedo.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_Albedo.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_Height.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_Height.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_Metalic.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_Metalic.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_Normal.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert1_Normal.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_AO.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_AO.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_Albedo.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_Albedo.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_Height.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_Height.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_Metalic.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_Metalic.png.meta
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_Normal.png
  MeltdownUnity/Assets/Models/Environmental/Texture Maps/24_Catwalk/T_24_Staricase V3 ALT_lambert2_Normal.png.meta
Labels: artist

#391 Gauge Script: Completion
  MeltdownUnity/Assets/Scripts/Managers/PuzzleManager/PuzzleManager_A.cs
  MeltdownUnity/Assets/Scripts/Managers/PuzzleManager/PuzzleManager_A.cs.meta
  MeltdownUnity/Assets/Scripts/Puzzle Elements/Steam Generator/GaugeIndicator.cs
Labels: programming

#416 Added Variables to moving platform
  MeltdownUnity/Assets/Scenes/Testing Scenes/PlayerMovementRedesign.unity
  MeltdownUnity/Assets/Scripts/Puzzle Elements/MovingPlatform/MovingPlatform.cs
Labels: programming
